Repository Software-Elegance/classif-ai, pull requests merged in 2022-08, with the labels that each got.

#2 Simple Quickstart
  README.md
Labels: documentation

#17 enabled frontend module
  frontend/build.gradle.kts
  frontend/src/main/kotlin/net/softel/ai/classify/DjlDemoWebApplication.kt
  frontend/src/main/kotlin/net/softel/ai/classify/backend/ObjectDetectionClient.kt
  frontend/src/main/kotlin/net/softel/ai/classify/controller/ObjectDetectionController.kt
  service/build.gradle.kts
  settings.gradle.kts
Labels: enhancement, good first issue

#18 (add) - Added contribution guide
  CONTRIBUTING.md
Labels: documentation, enhancement

#21 updated build github action pipeline
  .github/workflows/build.yml
  .gitignore
  build.gradle.kts
  common/build.gradle.kts
  common/src/main/java/net/softel/ai/classify/common/AmazonClientConfiguration.java
  frontend/build.gradle.kts
  service/build.gradle.kts
  service/gradle.properties
  service/src/test/java/net/softel/ai/classify/controller/PredictionControllerTest.java
Labels: bug, enhancement

#34 Refactor/model module
  .github/workflows/build.yml
  build.gradle.kts
  common/build.gradle.kts
  common/src/main/java/net/softel/ai/classify/models/InferenceResponse.java
  common/src/main/java/net/softel/ai/classify/models/InferredObject.java
  frontend/build.gradle.kts
  frontend/src/main/kotlin/net/softel/ai/classify/backend/ImageClassificationClient.kt
  frontend/src/main/kotlin/net/softel/ai/classify/backend/ObjectDetectionClient.kt
  model/build.gradle.kts
  model/settings.gradle.kts
  service/build.gradle.kts
  service/src/main/java/net/softel/ai/classify/ClassifySpringBootApplication.java
  service/src/main/java/net/softel/ai/classify/config/GitVersionConfig.java
  service/src/main/resources/application.properties
  settings.gradle.kts
Labels: enhancement, good first issue

#38 Add video streaming
  frontend/src/main/resources/static/video.html
  frontend/src/main/resources/templates/index.ftlh
  service/src/main/java/net/softel/ai/classify/config/StreamingConfig.java
  service/src/main/java/net/softel/ai/classify/controller/VideoStreamingController.java
  service/src/main/java/net/softel/ai/classify/service/impl/VideoStreamingService.java
  service/src/main/resources/mp4/sample_960x540.mp4
Labels: enhancement, good first issue

#45 UI/fix front page UI
  frontend/src/main/resources/static/assets/css/style.bundle.css
  frontend/src/main/resources/static/style.css
  frontend/src/main/resources/templates/index.ftlh
Labels: enhancement, good first issue, clean up

#46 object detection fix
  frontend/src/main/resources/templates/object-detection-files.ftlh
  frontend/src/main/resources/templates/object-detection-files.html
  service/src/main/java/net/softel/ai/classify/controller/RTSPController.java
Labels: enhancement, good first issue, clean up

#47 fix main page
  frontend/src/main/resources/templates/index.ftlh
Labels: enhancement, good first issue, clean up
